### ISSUE TITLE
Sensors can't be link to multiple lot, relation issue

### ISSUE THREAD

**Issue by Benvii** [OpenPathView/OPV_DBRest#21]
Sensors can't be link to multiple lot we need to check the relation, the API returns a list when requesting sensors.lot.

**Comment by philae-ael** [comment]
Relationship in sensor's ressource definition isn't properly set.
Replace
```python
lot = RessourceProxy("lot")
```
By
```python
class _rel:
    lot = RessourceProxy("lot")
```
